blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/sMAE3Na
    about: My personal Discord server
  - name: CosmeticsCore wiki
    url: https://cosmeticscore.devs.beer/
    about: Official wiki of CosmeticsCore
  - name: CosmeticsCore Spigot page
    url: https://www.spigotmc.org/resources/105324/
    about: Official Spigot page of CosmeticsCore
